# Generated by Django 4.2.16 on 2024-10-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroomusers_delete_chatroomuser'),
        ('products', '0022_alter_cartitem_user'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
