# Generated by Django 4.2.16 on 2024-10-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatroomuser_user_alter_message_sender'),
        ('products', '0023_alter_cartitem_user'),
        ('users', '0004_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
