# Generated by Django 4.2.16 on 2024-10-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatroom_users_chatroomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='Buyer', max_length=25),
        ),
    ]
