# Generated by Django 4.2.16 on 2024-10-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_create_chatroomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
