# Generated by Django 4.2.16 on 2024-10-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_at_product_description_product_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
