# Generated by Django 4.2.16 on 2024-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
