# Generated by Django 4.2.16 on 2024-10-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_standard_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='standard_price',
        ),
    ]
