# Generated by Django 4.2.16 on 2024-10-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_standard_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='in_cart',
        ),
    ]
