# Generated by Django 4.2.16 on 2024-10-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_cartitem_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
