# Generated by Django 4.2.16 on 2024-10-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_cartitem_in_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
